apiVersion: v1
kind: Service
metadata:
  name: book-recommender
  namespace: default
  labels:
    app: book-recommender
spec:
  type: LoadBalancer
  ports:
  - port: 8500
    protocol: TCP
    name: tf-serving-grpc
  - port: 8501
    protocol: TCP
    name: tf-serving-http
  selector:
    app: book-recommender